name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update submodules   
        run: git submodule update --init --recursive

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./server  



      - name: Run backend tests
        run: npm test
        working-directory: ./server



  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref_name == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and push NestJS Docker image
      - name: Set up Docker Buildx for backend
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-app:${{ github.sha }}

      
      - name: Set up Docker Buildx for frontend
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}
