name: CI/CD Pipeline

on:
push:
  branches:
    - dev
    - main
pull_request:
  branches:
    - dev
    - main

jobs:
test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    - name: Install dependencies
      run: npm install
      working-directory: ./server # Adjust the path if your NestJS app is in a different directory

    - name: Run tests
      run: npm test
      working-directory: ./server

build-and-push:
  runs-on: ubuntu-latest
  needs: test
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server # Adjust the path if your Dockerfile is in a different directory
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/your-nestjs-app:${{ github.sha }}